/**
 * Created by alexanderbol on 23/06/2016.
 */
export const FETCH_DATA_REQUEST_STARTED = "FETCH_DATA_REQUEST_STARTED";
export const FETCH_DATA_REQUEST_FINISHED = "FETCH_DATA_REQUEST_FINISHED";
export const FETCH_ORGANIZERS_REQUEST_SUCCEED = "FETCH_ORGANIZERS_REQUEST_SUCCEED";
export const FETCH_LOCATIONS_REQUEST_SUCCEED = "FETCH_LOCATIONS_REQUEST_SUCCEED";
export const FETCH_EVENTS_REQUEST_SUCCEED = "FETCH_EVENTS_REQUEST_SUCCEED";
export const ADD_NEW_EVENT_REQUEST_SUCCEED = "ADD_NEW_EVENT_REQUEST_SUCCEED";
export const EVENT_CHANGED = "EVENT_CHANGED"
